### ISSUE TITLE
Support new Forestry wood types

### ISSUE THREAD

**Issue by Adaptivity** [GoryMoon/MoarSigns#10]
Forestry now adds 4 new trees: https://github.com/ForestryMC/ForestryMC/commit/f862485a055e199045a7a97d2f1d3acacd26dc1c
They definitely should be supported.
Also, Loftwood from BiomesOPlenty now called Ethereal Wood: https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.7.10-2.1.x/src/main/resources/assets/biomesoplenty/lang/en_US.lang#L219
It should be renamed.

**Comment by GoryMoon** [comment]
Added and fixed in 1.2.0
