### ISSUE TITLE
Add support for Dr. Cyano's Base Metals

### ISSUE THREAD

**Issue by BrisingrAerowing** [GoryMoon/MoarSigns#18]
As per title, add support for [Dr. Cyano's Base Metals](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2352456-drcyanos-base-metals)

**Comment by BrisingrAerowing** [comment]
Also, as a side note, Tinker's Construct is available for 1.8.9 now.

**Comment by GoryMoon** [comment]
Both are added to 1.8.9 and 1.9
