### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by berryms** [GoryMoon/MoarSigns#24]
Hello! My Minecraft crashed when I had this mod installed, all of my signs from this mod are in my game and I don't want to take the mod out because of how many signs I had in there. Can you look at the crash report and see if I can do anything?
[crash-2016-07-15_01.33.29-server.txt](https://github.com/GoryMoon/MoarSigns/files/366663/crash-2016-07-15_01.33.29-server.txt)

**Comment by GoryMoon** [comment]
The crash has nothing to with me, it's something to do with a fence and the collision with the player.
