### ISSUE TITLE
Crash When Opening RFTools Machines with Moar Signs Toolbox in Hand

### ISSUE THREAD

**Issue by Darkosto** [GoryMoon/MoarSigns#35]
Hello,

I'm getting a consistent crash when right clicking on the RFTools Machines with a Moar Signs toolbox being held:

http://pastebin.com/SFssfezp
http://pastebin.com/MhR9hyA5

McJtyLib: 2.3.4
RFTools: 5.82
RFTools Dimensions: 4.53
Moar Signs: 4.2.2.8
MC: 1.10.2
Forge: 2221

This issue was also posted to McJty's tracker: https://github.com/McJty/McJtyLib/issues/29

Thank you!

**Comment by GoryMoon** [comment]
Sorry for not doing anything with this earlier, was doing some other fixes recently when I saw that I had fixed this but not published so now it's included in the latest version.
