### ISSUE TITLE
[Update] Can we see a possible release/update for 1.11+?

### ISSUE THREAD

**Issue by ZombieHDGaming** [GoryMoon/MoarSigns#38]
This is a great mod and it offers a lot of customization for something so simple. And just to say this now, I have tried updating this myself to 1.11.2. I've run into a few snags but nothing major (and for simplicity sakes, I removed any integration that required an outside API [NEI/JEI, Minetweaker] and didn't have many issues, this was of course for my use case). Most of the code is just updating methods and adding a line or two to a method to make it work as it should. I'd be glad to share some of the updated classes that I know work, but there may be some things you will need to rewrite :(

**Comment by GoryMoon** [comment]
Have had a working 1.11.2 build for a while now, haven't gotten to it to finish it up and releasing it, there are some integrations that needs fixing.

Have now started on it again so hopefully won't be to long.

**Comment by ZombieHDGaming** [comment]
Glad to hear it, if you don't mind me asking, what integrations need fixing? If you push a PR with the updated code and build file, I may be able to help out.

**Comment by GoryMoon** [comment]
Just some usual that have to do with this mod, making sure the correct items are used for crafting and if textures have changed and it if the name was changed

**Comment by GoryMoon** [comment]
Have uploaded a version to curse and pushed the changes to here.
