### ISSUE TITLE
More tinkers signs please!

### ISSUE THREAD

**Issue by Claycorp** [GoryMoon/MoarSigns#9]
I see that theres a few signs that work for the tinker metals but who doesn't want a nice purple or blue sign!
You could add the option for crafting the signs from battle sign heads and a stick too. That would give tons of options.

Also i think the nuggets and stick recipe was better. 6 ingots/blocks gets expensive quick per sign(s).

P.S. I really like the new GUI for signs. Its quite awesome!

**Comment by GoryMoon** [comment]
I will look into the other metals, it will be a while as I got a lot of other stuff.
Regarding the recipes I noticed it about 30min ago and I have fixed it, 55c5667b2db3f1deddbeb35c7975e81935b3e572, in v.1.1.2, go download it to get the fixed recipes.

**Comment by GoryMoon** [comment]
I think all metals from tinkers is now added in 1.2.0
